package Dominio;

public enum EquiposCopa implements Equipos {
    RealMadrid,
    Lugo,
    Atletico,
    Espanyol,
    Getafe,
    Elche,
    Girona,
    Huesca,
    Rayo,
    Alaves,
    Betis,
    Arandina,
    Amorebieta,
    Celta,
    Burgos,
    Mallorca,
    Castellon,
    Osasuna,
    RacingFerrol,
    Sevilla,
    Eibar,
    Athletic,
    Cartagena,
    Valencia,
    Barbastro,
    Barcelona,
    Malaga,
    RealSociedad,
    Tenerife,
    LasPalmas,
    Unionistas,
    Villareal
}
